name: Integration

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    inflint:
        name: Inflint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v4
              with:
                  run_install: true

            - name: Run Inflint
              run: pnpm inflint

    knip:
        name: Knip
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v4
              with:
                  run_install: true

            - name: Run Knip
              run: pnpm knip

    typescript:
        name: TypeScript
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v4
              with:
                  run_install: true

            - name: Run TypeScript
              run: pnpm run type-check

    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v4
              with:
                  run_install: true

            - name: Run build
              run: pnpm build

    cspell:
        name: CSpell
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v4
              with:
                  run_install: true

            - name: Run CSpell
              run: pnpm cspell

    prettier:
        name: Prettier
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v4
              with:
                  run_install: true

            - name: Run Prettier
              run: pnpm prettier
