name: Semantic Release

on:
    push:
        branches: [main]

jobs:
    release:
        name: Release version
        permissions:
            contents: write

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GH_TOKEN }}

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v4
              with:
                  run_install: true

            - name: Build "dist" folder
              run: pnpm build

            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4.2.0
              with:
                  extra_plugins: |
                      @semantic-release/changelog
                      @semantic-release/commit-analyzer
                      @semantic-release/git
                      @semantic-release/npm
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
